import numpy as np
from pathlib import Path

def collect_phase_diagram(folder, Ps_file, Pf_file, output, timechain, dt):
    """
    Collect raw data generated by phase diagram array job into
    a single txt file containing the processed results, including
    MSD scaling exponent, variance scaling exponent, mean longitudinal
    velocity, and effective diffusivity.
    
    Arguments:
        folder: directory containing the raw data files
        Ps_file: swim Peclet number file used to collect the data
        Pf_file: flow Peclet number file used to collect the data
        output: filename in which to store the processed results
        timechain: file containing the logscale timechain simulation times
        dt: timestep used to collect the raw data
    """
    # Read in Peclet numbers
    Ps_list = np.loadtxt(Ps_list)
    Pf_list = np.loadtxt(Pf_list)
    # Read in timechain
    tc = np.loadtxt(timechain, dtype=np.int64)

    # Write headers to file
    with open(output, "w") as f:
        f.write("Ps,Pf,alpha,beta,mean_vx,D_eff\n")

    # Iterate over each Peclet number
    for Ps, Pf, in zip(Ps_list, Pf_list):
        subfolder = f"{folder}/{Ps} {Pf}"
        mean_vx = get_mean_vx(subfolder, Ps, tc, dt)
        alpha = get_MSD_exponent(subfolder, tc, dt)
        beta, D_eff = get_variance_exponent_prefactor(subfolder, tc, dt)
        with open(output, "a") as f:
            f.write(f"{Ps},{Pf},{alpha},{beta},{D_eff},{mean_vx}\n")
            
def get_mean_vx(folder, Ps, tc, dt):
    """
    Calculate the mean instantaneous longitudinal velocity by taking the velocity
    at each pair of consecutive timesteps, separated by logscale blocks.
    
    Arguments:
        folder: directory containing the raw data for each trajectory
        Ps: swim Peclet number
        tc: logscale timechain
        dt: simulation timestep

    Returns:
        mean longitudinal velocity
    """
    # Calculate elapsed time
    t_elapsed = (tc[-1] - tc[0]) * dt
    # Find the second measurement of each logscale block (+1 to skip header)
    measurements = np.arange(1, len(tc)-1)[np.diff((tc[1:] - tc[:-1]) == 1)][::2] + 1
    # Initialise sum of x-velocities, particle counter
    sum_vx = 0.0
    particles = 0

    # Iterate over each particle
    for file in Path(folder).glob("*.txt"):
        # Increment number of particles
        particles += 1
        with open(file, "r") as f:
            # Initialise loop index
            i = -1
            # Calculate velocity once per logscale block
            for line in f:
                # Increment loop index
                i += 1
                if (i + 1) in measurements:
                    x_prev = np.fromstring(line, sep=',')[0]
                elif i in measurements:
                    x = np.fromstring(line, sep=',')[0]
                    sum_vx += (x - x_prev) / dt

    # Calculate and return mean velocity in terms of Ps
    return sum_vx / len(measurements) / particles / Ps        

def get_mean_vx2(folder, Ps, tc, dt):
    """
    Calculate the mean longitudinal velocity by dividing the difference between the
    first and last x-position by the total time elapsed between them.
    
    Arguments:
        folder: directory containing the raw data for each trajectory
        Ps: swim Peclet number
        tc: logscale timechain
        dt: simulation timestep

    Returns:
        mean longitudinal velocity
    """
    # Calculate elapsed time
    t_elapsed = (tc[-1] - tc[0]) * dt
    # Initialise sum of x-velocities, particle counter
    sum_vx = 0.0
    counter = 0

    # Iterate over each trajectory
    for file in Path(folder).glob("*.txt"):
        x_data = np.loadtxt(file, skiprows=1, usecols=1)
        sum_vx += (x_data[-1] - x_data[0]) / t_elapsed
        counter += 1

    # Calculate and return mean velocity by Ps
    return sum_vx / counter / Ps


